# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwesomeTutorial' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AwesomeTutorial
  pod 'lottie-ios'

  target 'AwesomeTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AwesomeTutorialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
